### PR TITLE
Update to Crystal v0.20

### PR DESCRIPTION
**Pull request by Sija**

### CODE REVIEW

**Comment by makenowjust** [comment]
Thanks for fixing. However test is failed, I'll try to fix test and merge it.

**Comment by Sija** [comment]
I've fixed syntax errors, but now there are some specific tests failing.

**Comment by makenowjust** [comment]
@Sija Thanks! and I fixed it already in my local repository.

**Comment by makenowjust** [comment]
Fixed in 143a181221d200bfbc49cc97cc308e8eabc46a98

**Pull request merged**
